
pipeline:
  build_push:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/redash
    tags:
      - ${DRONE_COMMIT_SHA:0:12}
      - latest
    when:
      event: [ push, tag ]

  helm_deploy:
    image: publicintegrity/drone-helm
    chart: ./charts/redash
    release: dash
    environment:
      - IMAGE_TAG=${DRONE_COMMIT_SHA:0:12}
    values: image.repository=publicintegrity/redash,image.tag=$${IMAGE_TAG},ingress.hosts[0]=$${HOST},externalPostgreSQL=postgresql://redash:$${PGPASSWORD}@$${PGHOST}:5432/redash,redis.redisPassword=$${REDISPASSWORD},env.REDASH_MAIL_SERVER=$${REDASH_MAIL_SERVER},env.REDASH_MAIL_USERNAME=$${REDASH_MAIL_USERNAME},env.REDASH_MAIL_PASSWORD=$${REDASH_MAIL_PASSWORD},env.REDASH_MAIL_DEFAULT_SENDER=$${REDASH_MAIL_DEFAULT_SENDER},env.REDASH_HOST=$${REDASH_HOST},env.REDASH_OFFICE365_CLIENT_ID=$${REDASH_OFFICE365_CLIENT_ID},env.REDASH_OFFICE365_CLIENT_SECRET=$${REDASH_OFFICE365_CLIENT_SECRET},REDASH_OFFICE365_OAUTH_ENABLED=True
    prefix:
    namespace: dash
    secrets: [ api_server, kubernetes_token, host, pgpassword, pghost, redispassword, redash_mail_server, redash_mail_username, redash_mail_password, redash_mail_default_sender, redash_host, redash_office365_client_id, redash_office365_client_secret ]
    skip_tls_verify: true
    when:
      event: deployment
      environment: production

  helm_deploy:
    image: publicintegrity/drone-helm
    chart: ./charts/redash
    release: dash-next
    environment:
      - IMAGE_TAG=${DRONE_COMMIT_SHA:0:12}
    values: image.repository=publicintegrity/redash,image.tag=$${IMAGE_TAG},ingress.hosts[0]=dash.publicintegrity.org,externalPostgreSQL=postgresql://redash:$${PGPASSWORD}@$${PGHOST}:5432/redash,redis.redisPassword=$${REDISPASSWORD},env.REDASH_MAIL_SERVER=$${REDASH_MAIL_SERVER},env.REDASH_MAIL_USERNAME=$${REDASH_MAIL_USERNAME},env.REDASH_MAIL_PASSWORD=$${REDASH_MAIL_PASSWORD},env.REDASH_MAIL_DEFAULT_SENDER=$${REDASH_MAIL_DEFAULT_SENDER},env.REDASH_HOST=https://dash.publicintegrity.org,env.REDASH_OFFICE365_CLIENT_ID=$${REDASH_OFFICE365_CLIENT_ID},env.REDASH_OFFICE365_CLIENT_SECRET=$${REDASH_OFFICE365_CLIENT_SECRET},REDASH_OFFICE365_OAUTH_ENABLED=True
    prefix:
    namespace: dash-next
    secrets: [ api_server, kubernetes_token, host, pgpassword, pghost, redispassword, redash_mail_server, redash_mail_username, redash_mail_password, redash_mail_default_sender, redash_host, redash_office365_client_id, redash_office365_client_secret ]
    skip_tls_verify: true
    when:
      event: deployment
      environment: staging

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
