
pipeline:
  # build:
  #   image: plugins/docker
  #   secrets: [ docker_username, docker_password ]
  #   repo: publicintegrity/redash

  helm_deploy:
    image: peloton/drone-helm
    chart: ./charts/redash
    release: dash
    values: image.repository=redash/redash,image.tag=6.0.0.b8537,ingress.hosts[0]=$${HOST},postgresql.postgresPassword=$${PGPASSWORD},postgresql.postgresHost=$${PGHOST},redis.redisPassword=$${REDISPASSWORD},env.REDASH_MAIL_SERVER=$${REDASH_MAIL_SERVER},env.REDASH_MAIL_USERNAME=$${REDASH_MAIL_USERNAME},env.REDASH_MAIL_PASSWORD=$${REDASH_MAIL_PASSWORD},env.REDASH_MAIL_DEFAULT_SENDER=$${REDASH_MAIL_DEFAULT_SENDER},env.REDASH_HOST=$${REDASH_HOST},env.REDASH_OFFICE365_CLIENT_ID=$${REDASH_OFFICE365_CLIENT_ID},env.REDASH_OFFICE365_CLIENT_SECRET=$${REDASH_OFFICE365_CLIENT_SECRET},REDASH_OFFICE365_OAUTH_ENABLED=True
    prefix:
    namespace: dash
    secrets: [ api_server, kubernetes_token, host, pgpassword, pghost, redispassword, redash_mail_server, redash_mail_username, redash_mail_password, redash_mail_default_sender, redash_host, redash_office365_client_id, redash_office365_client_secret ]
    skip_tls_verify: true
    when:
      event: deployment
      environment: production

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
