
pipeline:
  build:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/redash

  helm_deploy:
    image: peloton/drone-helm
    chart: ./charts/redash
    release: redash
    values: image.repository=publicintegrity/redash,image.tag=latest,ingress.hosts[0]=$${HOST},postgres.postgresPassword=$${PGPASSWORD},postgres.postgresHost=$${PGHOST},redis.redisPassword=$${REDISPASSWORD},env.REDASH_MAIL_SERVER=$${REDASH_MAIL_SERVER},env.REDASH_MAIL_USERNAME=$${REDASH_MAIL_USERNAME},env.REDASH_MAIL_PASSWORD=$${REDASH_MAIL_PASSWORD},env.REDASH_MAIL_DEFAULT_SENDER=$${REDASH_MAIL_DEFAULT_SENDER},env.REDASH_HOST=$${REDASH_HOST},env.REDASH_OFFICE365_CLIENT_ID=$${REDASH_OFFICE365_CLIENT_ID},env.REDASH_OFFICE365_CLIENT_SECRET=$${REDASH_OFFICE365_CLIENT_SECRET},REDASH_OFFICE365_OAUTH_ENABLED=True
    prefix:
    namespace: redash
    secrets: [ api_server, kubernetes_token, host, pgpassword, pghost, redispassword ]
    skip_tls_verify: true

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
